name: build

on:
  workflow_run:
    workflows: ["Super-Linter"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pytest
        pip install numpy
        pip install .
    - name: Test with pytest
      run: python -m pytest