name: build

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-16.04, ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup for Python 2.7 on Windows
      if: matrix.os == 'windows-2019' && matrix.python-version == '2.7'
      run: |
        choco install vcpython27
    - name: Install dependencies
      run: |
        pip install pytest
        pip install numpy
        pip install .
    - name: Test with pytest
      run: python -m pytest