name: Build Python Wheels for Manylinux

on:
  push:
    branches:
      - feature/wheel
  workflow_dispatch:
    inputs:
      repository: 
        description: 'The repository to upload the package to'
        required: true
        default: 'testpypi'

jobs:
  deploy:
    strategy:
      matrix:
        docker-image: [manylinux1_x86_64, manylinux_2_24_x86_64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker
        run: |
          docker pull quay.io/pypa/${{ matrix.docker-image }}
          docker run --rm -e PLAT=${{ matrix.docker-image }} -v ${{ github.workspace }}:/io quay.io/pypa/${{ matrix.docker-image }} /io/github-actions/build-wheels.sh
          ls wheelhouse/