name: Build Python Wheels and Upload Python Package

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      repository: 
        description: 'The repository to upload the package to'
        required: true
        default: 'testpypi'

jobs:
  deploy-windows:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: [x64, x86]
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        pip install pytest
        pip install numpy
        pip install .
    - name: Test with pytest
      run: python -m pytest
    - name: Build wheels
      run: |
        pip install wheel
        python setup.py bdist_wheel
  deploy-macos:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload  --repository testpypi dist/*