name: Upload Python Package

on:
  push:
    branches:
      - feature/wheel
  workflow_dispatch:
    inputs:
      repository: 
        description: 'The repository to upload the package to'
        required: true
        default: 'testpypi'

jobs:
  deploy:
    strategy:
      matrix:
        os: [macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload  --repository testpypi dist/*