name: Build Wheels

on:
  push:
    branches:
      - feature/wheel

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        with:
          output-dir: wheelhouse
        env:
          CIBW_BUILD: '{cp39}-{manylinux1_x86_64,manylinux10_x86_64,manylinux2014_aarch64,win32,win_amd64,macosx_x86_64} cp39-macosx_arm64'
    #      CIBW_BUILD: '{cp36,cp37,cp38,cp39}-{manylinux1_x86_64,manylinux10_x86_64,manylinux2014_aarch64,win32,win_amd64,macosx_x86_64} cp39-macosx_arm64'
          CIBW_ARCHS_LINUX: 'auto aarch64'
          CIBW_ARCHS_MACOS: 'auto arm64'
          CIBW_TEST_REQUIRES: 'pytest numpy==1.19.5'
          CIBW_TEST_COMMAND: pytest
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl